downstream_dependencies:
  - datanator_query_python
  - h1_hesc
  - wc_cli
email_notifications:
  - jonrkarr@gmail.com
  - yosefdroth@gmail.com
static_analyses:
  ignore_unused_requirements:
    - python_libsbml
  ignore_missing_requirements:
    - python-libsbml-experimental
