version: '3'


services:
  datanator:
    image: lzy7071/karrlabdatanator:latest
    restart: always
    stdin_open: true
    tty: true
    volumes: 
      - "../:/root/host/karr_lab"
      - "~/.wc:/root/.wc"

  flask:
    image: lzy7071/datanatorflask:latest
    restart: always
    entrypoint: bash
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"
    volumes: 
      - "../:/root/host/karr_lab"
      - "~/.wc:/root/.wc"

  mongo:
    image: mongo:4.0.10
    restart: always
    volumes:
      # - ./datanator/data_source/cache/mongo:/data/db
      - ../:/root/host/karr_lab
    ports:
      - "27017:27017"
    depends_on:
      - datanator

  mongosetup:
    image: mongo:4.0.10
    volumes:
      - ../:/root/host/karr_lab
    entrypoint: [ "bash", "/root/host/karr_lab/datanator/scripts/mongorestore.sh" ]
    restart: on-failure
    depends_on:
      - mongo

  mongoexpress:
    image: mongo-express:0.49.0
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    restart: always
    command: sh -c 'sleep 10 && tini -- node app'
