version: '3'


services:
  wc_env:
    image: karrlab/wc_env:latest
    restart: always
    entrypoint: bash
    stdin_open: true
    tty: true
    volumes: 
      - "../karr_lab:/root/host/karr_lab"

  postgres_service:
    image: circleci/postgres:11.2-alpine-ram
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: CommonSchema
    restart: always
    volumes: 
      - "../karr_lab:/root/host/karr_lab"

  mongo:
    image: 'bitnami/mongodb:4.1'
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=datanator
    volumes:
      - ./datanator/data_source/cache/mongo:/data/db
      - ../karr_lab:/home/host/karr_lab

  mongo-secondary:
    image: 'bitnami/mongodb:4.1'
    depends_on:
      - mongo
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongo
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_REPLICA_SET_NAME=datanator
    volumes:
      - ./datanator/data_source/cache/mongo_secondary:/data/db

  mongo-arbiter:
    image: 'bitnami/mongodb:4.1'
    depends_on:
      - mongo
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongo
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_REPLICA_SET_NAME=datanator

  mongoexpress:
    image: mongo-express:0.49.0
    restart: always
    ports:
      - "8081:8081"
    restart: always
    command: sh -c 'sleep 10 && tini -- node app'