version: '3'
services:
  wc_env:
    image: karrlab/wc_env:latest
    restart: always
    stdin_open: true
    tty: true
  depends_on:
    - postgres
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: 'ubuntu'
      POSTGRES_DB: 'CommonSchema'
    restart: always
    ports:
      - "5432:5432"
    volumes:
          - ./data/postgres:/var/lib/postgresql/data
