version: '3'

services:
  datanator:
    image: karrlab/wc_env
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "10001:5002"
    volumes: 
      - "../:/root/karr_lab"
      - "/home/zl/.wc:/root/.wc"
    entrypoint: >
      bash -c "python3 -m pip install pkg-utils
      && python3 -m pip install -e ~/karr_lab/wc_utils/
      && python3 -m pip install -e ~/karr_lab/karr_lab_aws_manager/
      && python3 -m pip install -e ~/karr_lab/datanator_query_python/
      && python3 -m pip install -e ~/karr_lab/datanator/
      && tail -f /dev/null"

  # mongo:
  #   image: mongo:4.0.10
  #   restart: always
  #   volumes:
  #     - ./datanator/data_source/cache/mongo:/data/db
  #     - ../:/root/karr_lab
  #   ports:
  #     - "27017:27017"
  #   depends_on:
  #     - datanator

  # mongosetup:
  #   image: lzy7071/mongo-curl:latest
  #   volumes:
  #     - ../:/root/karr_lab
  #   entrypoint: [ "bash", "/root/karr_lab/datanator/scripts/mongorestore.sh" ]
  #   restart: on-failure
  #   depends_on:
  #     - mongo

  # mongoexpress:
  #   image: mongo-express:0.49.0
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - mongo
  #   restart: always
  #   command: sh -c 'sleep 10 && tini -- node app'