version: '3'


services:
  wc_env:
    image: karrlab/wc_env:latest
    restart: always
    entrypoint: bash
    stdin_open: true
    tty: true
    volumes: 
      - "../:/root/host/karr_lab"

  postgres_service:
    image: circleci/postgres:11.2-alpine-ram
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: CommonSchema
    restart: always
    volumes: 
      - "../:/root/host/karr_lab"

  mongo:
    image: mongo:4.1
    restart: always
    volumes:
    - ./db_volumes/mongo:/data/db
    - ./docs/mongod.conf:/etc/mongod.conf
    - ../:/root/host/karr_lab
    ports:
    - "30001:27017"
    command: ["/usr/bin/mongod", "--config", "/etc/mongod.conf"]
 
  mongo_secondary:
    image: mongo:4.1
    restart: always
    volumes:
    - ./db_volumes/mongo_secondary:/data/db
    - ./docs/mongod.conf:/etc/mongod.conf
    - ../:/root/host/karr_lab
    ports:
    - "30002:27017"
    command: ["/usr/bin/mongod", "--config", "/etc/mongod.conf"]

  mongoexpress:
      image: mongo-express:0.49.0
      restart: always
      ports:
          - "8081:8081"
      restart: always
      environment:
          - WEB_USER='user'
          - WEB_PASS='pass'
      command: sh -c 'sleep 10 && tini -- node app'

volumes:
  mongodb_master_data:
    driver: local
