version: '3'
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: 'ubuntu'
      POSTGRES_DB: 'CommonSchema'
    restart: always
    ports:
      - "5432:5432"
    links:
      - wc_env
  wc_env:
    image: karrlab/wc_env:latest
    restart: always
    stdin_open: true
    tty: true
