version: '3'


services:

  wc_env:
    image: karrlab/wc_env:latest
    restart: always
    entrypoint: bash
    stdin_open: true
    tty: true
    volumes: 
      - "../../:/root/host/karr_lab"

  postgres_service:
    image: circleci/postgres:11.2-alpine-ram
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: CommonSchema
    restart: always
    volumes: 
      - "../../:/root/host/karr_lab"

  mongo-datanator-1:
    image: 'mongo-start'
    build: ./mongo-datanator-1
    ports:
      - "27017:27017" 
    volumes:
      - ./mongo-datanator-1/data:/data/db
    depends_on:
      - 'mongo-datanator-2'
      - 'mongo-datanator-3'
 
  mongo-datanator-2:
    image: 'mongo'
    restart: always
    command: --replSet datanator
    command: --config ./conf/mongo.conf
    ports:
      - "27018:27018"
    volumes:
      - ./mongo-datanator-2/data:/data/db
      - ./mongo-datanator-2/conf:/conf


  mongo-datanator-3:
    image: 'mongo'
    command: --replSet datanator
    command: --config ./conf/mongo.conf
    ports:
      - '27019:27019'
    volumes:
      - ./mongo-datanator-3/data:/data/db
      - ./mongo-datanator-3/conf:/conf
    restart: always    
    depends_on:
      - mongo-datanator-2  

  setup-rs:
    image: 'setup-rs'
    build: ./setup
    depends_on:
      - 'mongo-datanator-1'

  mongoexpress:
      image: mongo-express:0.49.0
      restart: always
      ports:
          - "8081:8081"
      restart: always
      environment:
          - WEB_USER='user'
          - WEB_PASS='pass'
      depends_on:
        - 'mongo-datanator-1'
        - 'setup-rs'
      command: sh -c 'sleep 10 && tini -- node app'
